version: "3"

services:
  jarvis:
    image: wkd1598/django-user:v6
    container_name: janginsung_django_web
    build: .
    command: python manage.py runserver 0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/janginsung_django_web
    expose:
      - "8000"
