version: "3"

services:
  jarvis:
    image: wkd1598/django-user:v6
    container_name: j_django

    #    build: .
    command: python manage.py runserver
    ports:
      - "8000:8000"
    volumes:
      - .:/my-django
    expose:
      - "8000"

  nginx:
    image: nginx
    container_name: j_nginx
    ports:
      - "80:80"
    depends_on:
      - jarvis